// Common API message placeholders.
// TODO: replace these with finalized product copy and localization-friendly messages.

module.exports = {
  SUCCESS: 'Operation completed successfully.',
  NOT_IMPLEMENTED: 'This endpoint is currently scaffolded and waiting for business logic.',
  PLACEHOLDER: 'Placeholder response generated by the backend foundation.'
};
