// Repository layer for reports_api.
// Responsibilities:
// - Interact with the Catalyst Data Store.
// - Keep persistence logic separate from service logic.

const catalyst = require('zcatalyst-sdk-node');
const { logger } = require('../utils/logger');

class ReportsRepository {
  /**
   * Inserts report metadata into the IntelligenceReports table.
   *
   * @param {object} req - Catalyst request object.
   * @param {object} metadata - The metadata to insert.
   * @returns {Promise<object>} The inserted row data.
   */
  async insertReportMetadata(req, metadata) {
    try {
      const catalystApp = catalyst.initialize(req);
      const datastore = catalystApp.datastore();
      const table = datastore.table('IntelligenceReports');

      logger.info('Inserting report metadata into IntelligenceReports table');

      // The ReportID (ROWID) is auto-generated by Catalyst
      const rowData = {
        AlertID: metadata.alertId,
        PdfUrl: metadata.pdfUrl,
        GeneratedDate: metadata.generatedDate
      };

      const result = await table.insertRow(rowData);
      logger.info('Successfully inserted report metadata', { rowId: result.ROWID });
      
      return result;
    } catch (error) {
      logger.error('Failed to insert report metadata', error);
      throw error;
    }
  }
}

module.exports = ReportsRepository;
