// Machine-readable error codes for DHAAL Intelligence Layer.
// Used by errorHandler.AppError and responseBuilder.error().
// Consistent across all backend modules.

module.exports = {
  // General errors
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  INVALID_REQUEST: 'INVALID_REQUEST',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',

  // Validation errors
  DISTRICT_NOT_FOUND: 'DISTRICT_NOT_FOUND',
  INVALID_DISTRICT: 'INVALID_DISTRICT',
  INVALID_DATE_RANGE: 'INVALID_DATE_RANGE',
  INVALID_PERIOD_TYPE: 'INVALID_PERIOD_TYPE',
  INVALID_CATEGORY: 'INVALID_CATEGORY',

  // Data access errors
  DATA_FETCH_ERROR: 'DATA_FETCH_ERROR',
  TABLE_NOT_FOUND: 'TABLE_NOT_FOUND',
  RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',

  // AI / Prediction errors
  PREDICTION_UNAVAILABLE: 'PREDICTION_UNAVAILABLE',
  MODEL_NOT_READY: 'MODEL_NOT_READY',

  // Anomaly errors
  DETECTION_ERROR: 'DETECTION_ERROR',
  INSUFFICIENT_DATA: 'INSUFFICIENT_DATA',

  // Report / PDF errors
  REPORT_GENERATION_FAILED: 'REPORT_GENERATION_FAILED',
  PDF_GENERATION_FAILED: 'PDF_GENERATION_FAILED',
  DOCUMENT_NOT_FOUND: 'DOCUMENT_NOT_FOUND'
};
